sudo: required

language: bash
services: docker

env:
  - DOCKER_IMAGE=nginx-rtmp

script:
  - docker build -t ${DOCKER_IMAGE} .

after_script:
  - docker images
  - docker run -d -p ${RTMP_PORT}:1935 -p ${HTTP_PORT}:80 -p ${HTTPS_PORT}:443 -t ${DOCKER_IMAGE}
  - docker ps -a
