version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - ${RTMP_PORT}:1935
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      - HTTP_PORT
      - HTTPS_PORT
      - RTMP_PORT
    volumes:
      - ./certs:/opt/certs
    networks:
      yptlive:
networks:
  yptlive: